modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/pipez/issues"
[[mods]]
modId = "pipez"
version = "${mod_version}"
displayName = "Pipez"
updateJSONURL = "https://update.maxhenkel.de/neoforge/pipez"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pipez"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Simple and efficient pipes'''
[[dependencies.pipez]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "mekanism"
type = "optional"
versionRange = "${mekanism_dependency}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.pipez]]
modId = "jei"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "theoneprobe"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"